package com.smarter56.waxberry.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.smarter56.waxberry.dao.GpsInfoModel;

import com.smarter56.waxberry.dao.GpsInfoModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gpsInfoModelDaoConfig;

    private final GpsInfoModelDao gpsInfoModelDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gpsInfoModelDaoConfig = daoConfigMap.get(GpsInfoModelDao.class).clone();
        gpsInfoModelDaoConfig.initIdentityScope(type);

        gpsInfoModelDao = new GpsInfoModelDao(gpsInfoModelDaoConfig, this);

        registerDao(GpsInfoModel.class, gpsInfoModelDao);
    }
    
    public void clear() {
        gpsInfoModelDaoConfig.getIdentityScope().clear();
    }

    public GpsInfoModelDao getGpsInfoModelDao() {
        return gpsInfoModelDao;
    }

}
